- speech/api/Makefile
An attempt to fix https://github.com/GoogleCloudPlatform/cpp-docs-samples/issues/11
Should alse result in faster builds.
Change-Id: Ie757a59e8c7f3a361ea9eefc21365abdf32c679c
> Build fewer files into googleapis.ar.

- .gitmodules
- .travis.yml
- bigtable/api/.clang-format
- bigtable/api/.gitignore
- bigtable/api/CMakeLists.txt
- bigtable/api/README.md
- bigtable/api/ci/build-linux.sh
- bigtable/api/ci/build-macosx.sh
- bigtable/api/ci/cache-linux.sh
- bigtable/api/ci/install-linux.sh
- bigtable/api/ci/install-macosx.sh
- bigtable/api/create_instance.cc
- bigtable/api/delete_instance.cc
- bigtable/api/docker/Dockerfile.fedora
- bigtable/api/docker/Dockerfile.ubuntu
- bigtable/api/list_instances.cc
Create a simple program to list the Cloud Bigtable instances in a project, as well as the supporting `cmake` files, Travis build scripts, Dockerfiles to test with different distributions and compilers, and supporting documentation.
> Initial bigtable/api example with automated builds. (#2)

- bigtable/api/CMakeLists.txt
- bigtable/api/README.md
- bigtable/api/parse_taq_line.cc
- bigtable/api/parse_taq_line.h
- bigtable/api/read_rows.cc
- bigtable/api/taq.proto
- bigtable/api/upload_taq.cc
- bigtable/api/upload_taq_batch.cc
* Start on example for the ReadRow() api.
I refactored the code to parse TAQ files to a separate file and
also cleaned up the protos to represent TAQ quotes.
* Make read_row and upload_taq_batch work together.
* Rename to read_rows.
* Add missing #include for Linux.
* Fix errors on g++ builds.
* Address feedback from PR review.
* Use chain filters instead of condition filters.
* Simplify example of chunk processing.
Merge into a single value using value_size() instead of using
the io::ZeroCopy* protobuf streams.  The latter might be more
efficient, but they complicate the example.
> Create an example of ReadRows()

- iot/mqtt-ciotc/mqtt_ciotc.c
The default keep-alive for other Paho MQTT libraries is 60 seconds, and we recommend 60 seconds in our docs.
> Change keepAliveInterval to 60s per IoT docs

- iot/mqtt-ciotc/mqtt_ciotc.c
Conversion of milliseconds to microseconds requires `/ 1000` => `* 1000`
> iot_mqtt_publish: fix conversion of ms to us

- speech/api/Dockerfile
`make` is now deprecated and the 1.26.0 binary built by `make` hits this bug: https://github.com/grpc/grpc/issues/21501
When building 1.26.0 with cmake, it's fine.
> chore: upgrade gRPC to 1.26.0

- cloud-run-hello-world/Dockerfile
With this change the image size is about 1.3MiB compressed, and GCR
says that it is less than 0.5MiB compressed. That makes for faster
startup times.
> feat: reduce the Cloud Run Hello World image size

- populate-bucket/README.md
Missed some options, normally they are not needed, but if you are
managing multiple projects with clusters in multiple regions the command
may be ambiguous without them.
> doc: missing options in get-credentials

- gcs-indexer/refresh_index_for_bucket.cc
Now that the GitHub action is actually running, it caught one file
formatted incorrectly.
> cleanup: fix c++ formatting

- ci/cloudbuild.yaml
- ci/devtools.Dockerfile
This will let us run builds in Cloud Build, which then can run
integration tests.
> ci: initial build scripts for Cloud Build

- gcs-indexer/cloudbuild.yaml
This seems to timeout with a cold cache, which requires re-starting the
PR build manually. Setting to a higher value to avoid the timeouts.
> ci: avoid timeouts in gcs-indexer

- getting-started/README.md
- getting-started/gcs_indexing.cc
- getting-started/gcs_indexing.h
- getting-started/index_gcs_prefix.cc
Tolerate higher latency by sending messages via a push
subscription in Cloud Pub/Sub. It also avoids introducing more
infrastructure.
> cleanup: skip eventarc using Pub/Sub

- getting-started/README.md
This time I eliminated the need to create a service account. I also
fixed the expected output from `select count(*)` and a mistake in the
cleanup steps.
> doc: another pass fixing the Getting Started guide

- ci/cloudbuild.yaml
- cloud-run-hello-world/cloudbuild.yaml
- getting-started/gke/cloudbuild.yaml
- populate-bucket/cloudbuild.yaml
Kaniko used to crash with the release version circa v1.6.0, we have
moved to v1.8.1, and in other repositories we have no problems with the
release version.
> ci: use release version of kaniko

- getting-started/Dockerfile
Using HEAD in documentation and builds is bound to break sooner or
later. This pins the release of `vcpkg`. In a separate effort, I am
configuring renovatebot to keep this updated.
> chore: pin vcpkg version in getting started guide

- .github/renovate.json
Another iteration configuring renovatebot.  The dashboard says
(I think) that the `vcpkg` versions do not follow semver (which
they don't).  Try something less strict.
If curious, the errors I am looking at are here:
https://app.renovatebot.com/dashboard#github/GoogleCloudPlatform/cpp-samples/662800511
> chore: more renovatebot configuration

- gcs-fast-transfers/gcs_fast_transfers.cc
- speech/api/streaming_transcribe.cc
- speech/api/streaming_transcribe_singlethread.cc
- speech/api/transcribe.cc
These files may be (and often are) binary files, and on Windows one
must use `std::ios::binary` or bad things happen.
Motivated by #187 and possibly other things.
> fix: use `std::ios::binary` to open files

- speech/api/.gitignore
- speech/api/CMakeLists.txt
- speech/api/async_transcribe.cc
- speech/api/parse_arguments.cc
- speech/api/parse_arguments.h
- speech/api/streaming_transcribe.cc
- speech/api/streaming_transcribe_singlethread.cc
- speech/api/transcribe.cc
- speech/api/vcpkg.json
I think the specific problem that made this example fail affected all
platforms, namely, that it read 0 bytes from a file (this can happen at
EOF if the file is a multiple of the read buffer size), and then tried
to send this 0-byte blob to the service.
To get the code working on Windows I had to replace `getopt(1)` with
something more portable, I chose Boost::program_options because we use
it in other places.
I also made a pass making the code look more idiomatic for C++11: prefer
using range-based for loops, prefer returning values, use exceptions
(instead of `nullptr`) to signal errors, etc.
We should make a second pass fixing this code to use the C++ client
library, calling gRPC directly is exceedingly painful.
Fixes #187
> fix: get the speech/ example working on Windows

- ci/cloudbuild.yaml
This should make the following steps more efficient when there is a change to the vcpkg baseline.
> ci: more vcpkg warmup

- cloud-run-hello-world/CMakeLists.txt
- gcs-fast-transfers/CMakeLists.txt
- gcs-fast-transfers/vcpkg.json
- getting-started/CMakeLists.txt
- getting-started/update/CMakeLists.txt
- iot/mqtt-ciotc/CMakeLists.txt
- iot/mqtt-ciotc/vcpkg.json
- populate-bucket/CMakeLists.txt
- populate-bucket/vcpkg.json
Consistently require CMake >= 3.20, and prefer using
`target_compile_features()` to set the C++ standard.
> ci: modernize CMake files

- speech/api/CMakeLists.txt
- speech/api/streaming_transcribe_singlethread.cc
I am less certain of this change, and that is why it is in a separate PR.
Obviously the code is longer, and it makes a lot of use of callbacks and futures, that (maybe) makes it less readable.
OTOH, the previous approach had all kinds of bad practices embedded in it, and it was probably hard to see how would one scale beyond a single request running in a loop in `main()`.
> cleanup(speech): use client library for async streaming

- ci/devtools.Dockerfile
- cloud-run-hello-world/Dockerfile
- getting-started/Dockerfile
- getting-started/gke/index_gcs.cc
- getting-started/index_gcs_prefix.cc
- populate-bucket/Dockerfile
- populate-bucket/populate_bucket.cc
With this new release we get a newer version of `google-cloud-cpp`, which deprecates a number of functions. I updated the examples to match.
> chore(deps): update to the latest vcpkg release

- .cmake-format.py
- CMakeLists.txt
- bigquery/write/CMakeLists.txt
- ci/cloudbuild.yaml
- gcs-fast-transfers/CMakeLists.txt
- getting-started/CMakeLists.txt
- getting-started/update/CMakeLists.txt
- iot/mqtt-ciotc/CMakeLists.txt
- populate-bucket/CMakeLists.txt
- speech/api/CMakeLists.txt
Maintaining the YAML file for Google Cloud Build was getting tedious. Using a top-level CMake file would be easier to maintain, all we would need to do is add new directories to the sample list.  The top-level CMake file is a super build. This is to validate the configure+build steps in each directory work. In contrast, using `add_subdirectory()` would build everthing, but would configure only once, using the top-level CMake file.
> ci: switch builds to top-level CMake file

- cloud-run-hello-world/Dockerfile
Cut some stages. We used them before to manually cache things, but with Kaniko this is no longer needed.
> cleanup: simplify Dockerfile

- bigquery/write/single_threaded_write.cc
- ci/devtools.Dockerfile
- cloud-run-hello-world/Dockerfile
- getting-started/Dockerfile
- populate-bucket/Dockerfile
- speech/api/streaming_transcribe.cc
- speech/api/streaming_transcribe_coroutines.cc
- speech/api/streaming_transcribe_singlethread.cc
This version the changes to `google-cloud-cpp` that remove `ExperimentalTag{}` from bi-directional streaming RPCs.
> chore(deps): update vcpkg to v2023.01.09

- speech/api/README.md
address https://github.com/GoogleCloudPlatform/cpp-samples/issues/252
> docs(speech/api): remove - and add gcloud cli command

- speech/api/streaming_transcribe_coroutines.cc
- speech/api/streaming_transcribe_singlethread.cc
Prevent https://github.com/GoogleCloudPlatform/cpp-samples/issues/252 from occurring
To verify, pass in command with an extra '-' so the arguments don't correctly parse:
```
pushd speech/api   
cmake -S. -B.build -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake
cmake --build .build       
GOOGLE_CLOUD_CPP_USER_PROJECT=alevenb-test .build/streaming_transcribe_singlethread ---bitrate 16000 resources/audio.raw
❯ GOOGLE_CLOUD_CPP_USER_PROJECT=alevenb-test .build/streaming_transcribe_singlethread ---bitrate 16000 resources/audio.raw
Standard C++ exception thrown: unrecognised option '---bitrate'
Usage:
streaming_transcribe_singlethread [--bitrate N] audio.(raw|ulaw|flac|amr|awb)
```
No more segfaulting 🥳
> fix(speech/api): prevent segfault when arguments aren't parsed correctly

- .github/renovate.json
I took this from https://docs.renovatebot.com/presets-schedule/#scheduleautomergemonthly
Fixes #275
> ci: fix schedule so it can parse

- .editorconfig
- .mdformat.toml
- ci/builds/checkers.sh
Example changes: https://github.com/GoogleCloudPlatform/cpp-samples/pull/280
This is a subset of google-cloud-cpp/ci/builds/checkers.sh
I've only run this locally. In the future, maybe we can set it up on cloudbuild, but for now I just need a script for formatting my changes.
> feat: add a checkers.sh script

- pubsub-open-telemetry/README.md
- pubsub-open-telemetry/quickstart.cc
Move non-obvious types/namespaces into the region of the application used in our docs.
We define `GOOGLE_CLOUD_PROJECT=...` and `GOOGLE_CLOUD_TOPIC=...`, so use them as arguments when running the quickstart.
> cleanup: pubsub-otel

- .github/renovate.json
One of our samples has a python component. (It is temporary. We only use python because there is currently a gap in the C++ API).
Suppress `renovate-bot` updates of the requirements for that program. The PRs are more distracting than valuable.
We do the same thing in `google-cloud-cpp`:
https://github.com/googleapis/google-cloud-cpp/blob/68a939076eb6b824e3f6c3838c8f85cdced2b584/.github/renovate.json#L7-L9
> chore: no renovate-bot python updates
