GoogleCloudPlatform/cpp-samples

- speech/api/Makefile
Change-Id: Ic50cfb7928524e17c039c39986a5ea37a1ec9864
> Remove obsolete makefile var SPEECH_PROTO_PATH.

- README.md
- speech/api/README.md
Also, add more details around cloning and building https://github.com/googleapis/googleapis.
> Add note that code only compiles on Linux.

- speech/api/Makefile
Fixes https://github.com/GoogleCloudPlatform/cpp-docs-samples/issues/13
> Use known files on cloud storage for tests.

- bigtable/api/CMakeLists.txt
- bigtable/api/cmake/CompileProtos.cmake
- bigtable/api/create_table.cc
- bigtable/api/resources/download_taq.sh
- bigtable/api/taq.proto
- bigtable/api/upload_taq.cc
- bigtable/api/upload_taq_batch.cc
Two separate examples, one for the MutateRow() API and another for the MutateRows() API.
Also include a script to download the data used in the examples.
> Implement MutateRow() and MutateRows() examples.

- CONTRIBUTING.md
This makes the links clickable from the GitHub web UI.
> Fixed Markdown syntax for inline links.

- .appveyor.yml
- .gitignore
- bigtable/api/CMakeLists.txt
- bigtable/api/ci/build-windows.ps1
- bigtable/api/ci/install-windows.ps1
- bigtable/api/parse_taq_line.cc
- bigtable/api/read_rows.cc
- bigtable/api/upload_taq_batch.cc
The Windows build was not detecting all errors, fixed that.  Also fixed problems with package detection on Windows (the packaging changed).  And finally fixed some warnings issued by MSVC on x86 builds.
> Cleanup windows build

- iot/mqtt-ciotc/mqtt_ciotc.c
Just moving the opts region tag so that it doesn't include some JWT options.
> Move opts region tag

- iot/mqtt-ciotc/mqtt_ciotc.c
Also has small fix for when [you pass the deviceid as the first parameter](https://github.com/GoogleCloudPlatform/cpp-docs-samples/issues/31).
> Adds exponential backoff to MQTT device example

- iot/mqtt-ciotc/mqtt_ciotc.c
Makes the code more readable, less error prone.
> Add struct member names to options initialization.

- iot/mqtt-ciotc/.gitignore
- iot/mqtt-ciotc/README.md
- iot/mqtt-ciotc/docker/Dockerfile
- iot/mqtt-ciotc/mqtt_ciotc.c
- iot/mqtt-ciotc/setup_device.sh
* Add a command to properly create the environment on GCP
* Fix the following bugs:
- Topic was not calculated
- Default key type is now configurable
> * Simplify Docker image and reduce size

- ci/kokoro/build.sh
- speech/api/Dockerfile
- speech/api/ci/kokoro/build.sh
> testing: fix a bug in ci/kokoro/build.sh and cache devtools image

- README.md
- ci/kokoro/build.sh
Preview at: https://github.com/tmatsuo/cpp-docs-samples/tree/badge
> docs: add a build badge

- ci/kokoro/common.cfg
- speech/api/ci/kokoro/build.sh
> testing: add the service account key for integration tests

- iot/mqtt-ciotc/Makefile
- iot/mqtt-ciotc/README.md
> fix: add `-ljansson` for iot sample

- iot/mqtt-ciotc/.clang-tidy
- iot/mqtt-ciotc/Makefile
- iot/mqtt-ciotc/ci/kokoro/build.sh
- iot/mqtt-ciotc/docker/Dockerfile
- iot/mqtt-ciotc/mqtt_ciotc.c
* also update to ubuntu 18.04
fixes #63
> testing: run clang-tidy for iot sample

- iot/mqtt-ciotc/mqtt_ciotc.c
> fix[iot]: construct the correct topic name

- iot/mqtt-ciotc/README.md
- iot/mqtt-ciotc/ci/kokoro/build.sh
- iot/mqtt-ciotc/docker/Dockerfile
- iot/mqtt-ciotc/setup_device.sh
- iot/mqtt-ciotc/test_mqtt_ciotc.sh
> testing[iot]: implement integration tests for iot sample

- iot/mqtt-ciotc/test_mqtt_ciotc.sh
* also clean up the resources with bash trap
fixes #77 
Now we use unique resource names which contains date string, and cleanup the resources on bash exit trap. It is still possible that those resources are leaked, but even in that case, we can safely delete those resources if the date field is old enough.
> testing[iot]: use unique resource names for tests

- iot/mqtt-ciotc/ci/kokoro/build.sh
- iot/mqtt-ciotc/test_mqtt_ciotc.sh
- speech/api/ci/kokoro/build.sh
> testing: suppress log output for some operations

- speech/api/Dockerfile
fixes #82 
At least, it passes locally.
> Pin grpc to v1.25.0 release

- cloud-run-hello-world/Dockerfile
- cloud-run-hello-world/README.md
- cloud-run-hello-world/bootstrap-cloud-run-hello.sh
- cloud-run-hello-world/cloud_run_hello.cc
Also improve the documentation in the Dockerfile and the README.md
files.
Fixes #91
> feat: make greeting configurable

- ci/kokoro/build.sh
example of failure:
https://source.cloud.google.com/results/invocations/708a8271-0687-448d-b3e9-b3988d317981/targets
> testing: fix error in the test driver

- cloud-run-hello-world/CMakeLists.txt
- cloud-run-hello-world/Dockerfile
- cloud-run-hello-world/cloud_run_hello.cc
This will be used to make the docsite cleaner.
> doc: use region tags

- cloud-run-hello-world/CMakeLists.txt
- cloud-run-hello-world/Dockerfile
- cloud-run-hello-world/cloud_run_hello.cc
Make region tags consistent with Cloud Run's region tags. Will de-duplicate in the future
> Update region tags

- gcs-indexer/Dockerfile
- gcs-indexer/bootstrap-gcs-indexer.sh
- gcs-indexer/cloudbuild.yaml
- gcs-indexer/generate_randomly_named_objects_config.py
- gcs-indexer/refresh_index_for_bucket_config.py
- gcs-indexer/vcpkg.json
The Dockerfile had gone stale, it no longer built. I just switched to
Ubuntu:20.04 because we test our libraries with it routinely. The
previous base (Alpine:edge) is cool, but we do not test with it
regularly, so things break. I also simplified the Cloud Build
configuration.
> cleanup: fix and cleanup Dockerfile

- .gitignore
- gcs-fast-transfers/CMakeLists.txt
- gcs-fast-transfers/download.cc
- gcs-fast-transfers/gcs_fast_transfers.cc
- gcs-fast-transfers/gcs_fast_transfers.h
- gcs-fast-transfers/upload.cc
- gcs-fast-transfers/vcpkg.json
Do some refactoring of the common functions for uploads and downloads.
> feat: create example for parallel uploads

- cloud-run-hello-world/bootstrap-cloud-run-hello.sh
> Fix for https://github.com/GoogleCloudPlatform/cpp-samples/issues/134

- getting-started/CMakeLists.txt
- getting-started/README.md
- getting-started/gcs_index_scheduler.cc
- getting-started/gcs_objects.sql
- getting-started/project.toml
Part of the work for #138 
I would like feedback on the README file the most.  Is it too long?  Should we add more explanations as to what is going on?
Is it too complicated to have two separate functions?  I can probably do it with one, but the C++ code will get more complicated as it would need to decide how to handle events from one topic different than events from a different topic.
I might not fix all issues in this PR, but will captured them in the tracking bug.
> feat: complete commands to deploy and cleanup

- getting-started/README.md
> doc: wrap up getting started README file

- getting-started/Dockerfile
- getting-started/gke/README.md
- getting-started/gke/cloudbuild.yaml
- getting-started/gke/index_gcs.cc
- getting-started/gke/print-deployment.py
In this iteration I completed the documentation to create the GKE
cluster, deploy the application to said cluster, and run some test data
through the application. GKE needs a lot more configuration, and some
advanced use-cases (scaling up automatically) are beyond what we should
cover in a "Getting Started with C++" guide.
> doc: another iteration on GKE example

- speech/api/README.md
Let's make these examples easier to use for folks on other platforms.
Motivated by #170
> doc: add notes for Windows and macOS

- ci/devtools.Dockerfile
- populate-bucket/Dockerfile
This will help with other updates in the future.
> chore(deps): update vcpkg baseline

- cloud-run-hello-world/CMakeLists.txt
- cloud-run-hello-world/Dockerfile
- cloud-run-hello-world/cloud_run_hello.cc
- cloud-run-hello-world/cloudbuild.yaml
- cloud-run-hello-world/vcpkg.json
Use the functions framework to simplify the code in this example. Also
use `vcpkg` to install all the dependencies. We need this as there is no
alpine package for the functions framework. As a side benefit, this
makes it more consistent with other examples.
> cleanup: simplify the Cloud Run "Hello World"

- ci/devtools.Dockerfile
I had enabled auto-merge so I need a new PR to address your review comment.
> ci: fix comment in Dockerfile

- CMakeLists.txt
- ci/builds/setup-bazel.sh
- ci/builds/setup-conda.sh
- ci/builds/setup-vcpkg.sh
- ci/cloudbuild-setup-bazel.yaml
- ci/cloudbuild-setup-conda.yaml
- ci/cloudbuild-setup-vcpkg.yaml
- ci/cloudbuild.yaml
- ci/conda.Dockerfile
- ci/devtools.Dockerfile
- ci/triggers/cpp-samples-pr.yaml
- ci/triggers/setup-bazel-pr.yaml
- ci/triggers/setup-conda-pr.yaml
- ci/triggers/setup-vcpkg-pr.yaml
- setup/.bazelrc
- setup/BUILD.bazel
- setup/CMakeLists.txt
- setup/README.md
- setup/WORKSPACE.bazel
- setup/hello_world.cc
- setup/vcpkg.json
This adds some examples to be used in the "how to set up your development environment" guide.
> feat: setting up C++ devevelopment environment

- speech/api/streaming_transcribe_singlethread.cc
Fixes https://github.com/GoogleCloudPlatform/cpp-samples/issues/252
> fix(speech/api): fix segfault due to pass by reference

- pubsub-open-telemetry/.jaeger_config.yaml
- pubsub-open-telemetry/CMakeLists.txt
- pubsub-open-telemetry/README.md
- pubsub-open-telemetry/publisher.md
- pubsub-open-telemetry/publisher_jaeger.cc
- pubsub-open-telemetry/vcpkg.json
Also did some cleanup for other examples
Only added cmake support for now.
> impl(pubsub-otel): add jaeger example
